version: "3.8"

services:
  evolution-api:
    container_name: evolution_api_local
    image: evoapicloud/evolution-api:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - evolution-postgres
    environment:
      - SERVER_URL=http://localhost:8080
      - ENV=dev
      
      # Autenticação
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=429683C4C977415CAAFCCE10F7D57E11
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      
      # Conexão com o Banco de Dados (Postgres)
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://admin:admin123@evolution-postgres:5432/evolution_db?schema=evolution_api
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_local
      
      # Cache Local (Sem Redis para economizar RAM)
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
      
      # CORS
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
    
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - n8n_net

  evolution-postgres:
    container_name: evolution_postgres_local
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=evolution_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_net

volumes:
  evolution_instances:
  postgres_data:

networks:
  n8n_net:
    driver: bridge